export const subscriptionKeys = [
    { key: "id" },
    { key: "lawFirm" },
    { key: "plan" },
    { key: "startDate" },
    { key: "renewalDate" },
    { key: "billingCycle" },
    { key: "price" },
    { key: "status" },
]

export const oneTimeKeys = [
    { key: "id" },
    { key: "productName" },
    { key: "productType" },
    { key: "category" },
    { key: "client" },
    { key: "orderDate" },
    { key: "price" },
    { key: "status" },
]

export const customKeys = [
    { key: "id" },
    { key: "client" },
    { key: "vendor" },
    { key: "productType" },
    { key: "category" },
    { key: "orderDate" },
    { key: "status" },
]

export const subscriptionRows = [
    "ID", "Law Firm", "Plan", "Start Date", "Renewal Date", "Billing Cycle", "Price", "Status",
]

export const subscriptionOrders = [
    {
        "id": 1,
        "lawFirm": "Bautista Law Office",
        "plan": "Premium",
        "startDate": new Date(1970, 0, 1),
        "renewalDate": new Date(1970, 0, 1),
        "billingCycle": "Monthly",
        "price": 1000,
        "status": "Active",
    },
    {
        "id": 2,
        "lawFirm": "Simple Law Office",
        "plan": "Free",
        "startDate": new Date(2020, 0, 1),
        "renewalDate": new Date(2030, 0, 1),
        "billingCycle": "Monthly",
        "price": 1000,
        "status": "Active",
    },
    {
        "id": 3,
        "lawFirm": "Very Long Title Law Firm",
        "plan": "Premium",
        "startDate": new Date(2019, 11, 31),
        "renewalDate": new Date(2027, 11, 31),
        "billingCycle": "Monthly",
        "price": 1000,
        "status": "Active",
    },
    {
        "id": 4,
        "lawFirm": "Rizal Law Offices",
        "plan": "Free",
        "startDate": new Date(1970, 0, 1),
        "renewalDate": new Date(1970, 0, 1),
        "billingCycle": "Monthly",
        "price": 1000,
        "status": "Active",
    },
    {
        "id": 5,
        "lawFirm": "Ignacio Law Office",
        "plan": "Premium",
        "startDate": new Date(1970, 0, 1),
        "renewalDate": new Date(1970, 0, 1),
        "billingCycle": "Monthly",
        "price": 1000,
        "status": "Active",
    },
    {
        "id": 6,
        "lawFirm": "Bautista Law Office",
        "plan": "Premium",
        "startDate": new Date(1970, 0, 1),
        "renewalDate": new Date(1970, 0, 1),
        "billingCycle": "Monthly",
        "price": 1000,
        "status": "Active",
    },
    {
        "id": 7,
        "lawFirm": "Simple Law Office",
        "plan": "Free",
        "startDate": new Date(2020, 0, 1),
        "renewalDate": new Date(2030, 0, 1),
        "billingCycle": "Monthly",
        "price": 1000,
        "status": "Active",
    },
    {
        "id": 8,
        "lawFirm": "Very Long Title Law Firm",
        "plan": "Premium",
        "startDate": new Date(2019, 11, 31),
        "renewalDate": new Date(2027, 11, 31),
        "billingCycle": "Monthly",
        "price": 1000,
        "status": "Active",
    },
    {
        "id": 9,
        "lawFirm": "Rizal Law Offices",
        "plan": "Free",
        "startDate": new Date(1970, 0, 1),
        "renewalDate": new Date(1970, 0, 1),
        "billingCycle": "Monthly",
        "price": 1000,
        "status": "Active",
    },
    {
        "id": 10,
        "lawFirm": "Ignacio Law Office",
        "plan": "Premium",
        "startDate": new Date(1970, 0, 1),
        "renewalDate": new Date(1970, 0, 1),
        "billingCycle": "Monthly",
        "price": 1000,
        "status": "Active",
    },
    {
        "id": 11,
        "lawFirm": "Bautista Law Office",
        "plan": "Premium",
        "startDate": new Date(1970, 0, 1),
        "renewalDate": new Date(1970, 0, 1),
        "billingCycle": "Monthly",
        "price": 1000,
        "status": "Active",
    },
    {
        "id": 12,
        "lawFirm": "Simple Law Office",
        "plan": "Free",
        "startDate": new Date(2020, 0, 1),
        "renewalDate": new Date(2030, 0, 1),
        "billingCycle": "Monthly",
        "price": 1000,
        "status": "Active",
    },
    {
        "id": 13,
        "lawFirm": "Very Long Title Law Firm",
        "plan": "Premium",
        "startDate": new Date(2019, 11, 31),
        "renewalDate": new Date(2027, 11, 31),
        "billingCycle": "Monthly",
        "price": 1000,
        "status": "Active",
    },
    {
        "id": 14,
        "lawFirm": "Rizal Law Offices",
        "plan": "Free",
        "startDate": new Date(1970, 0, 1),
        "renewalDate": new Date(1970, 0, 1),
        "billingCycle": "Monthly",
        "price": 1000,
        "status": "Active",
    },
    {
        "id": 15,
        "lawFirm": "Ignacio Law Office",
        "plan": "Premium",
        "startDate": new Date(1970, 0, 1),
        "renewalDate": new Date(1970, 0, 1),
        "billingCycle": "Monthly",
        "price": 1000,
        "status": "Active",
    },
]

export const oneTimeRows = [
    "ID", "Product Name", "Type", "Category", "Client", "Order Date", "Price", "Status",
]

export const oneTimeOrders = [
    {
        "id": 1,
        "productName": "Hammer-Logo",
        "productType": "Logo",
        "category": "Hammer",
        "client": "Bautista Law Office",
        "orderDate": new Date(2026, 6, 5),
        "price": 1000,
        "status": "Paid",
    },
    {
        "id": 2,
        "productName": "Header-Text",
        "productType": "Copywrite",
        "category": "Header",
        "client": "Simple Law Office",
        "orderDate": new Date(2026, 6, 5),
        "price": 1000,
        "status": "Paid",
    },
    {
        "id": 3,
        "productName": "Office-Image",
        "productType": "Photo",
        "category": "Office",
        "client": "Rizal Law Office",
        "orderDate": new Date(2026, 0, 1),
        "price": 1000,
        "status": "Paid",
    },
    {
        "id": 4,
        "productName": "Blue-Template",
        "productType": "Template",
        "category": "Blue",
        "client": "Shigetora Law Firm",
        "orderDate": new Date(2027, 6, 27),
        "price": 1000,
        "status": "Paid",
    },
    {
        "id": 5,
        "productName": "Hammer-Logo",
        "productType": "Logo",
        "category": "Hammer",
        "client": "Bautista Law Office",
        "orderDate": new Date(2026, 6, 5),
        "price": 1000,
        "status": "Paid",
    },
    {
        "id": 6,
        "productName": "Header-Text",
        "productType": "Copywrite",
        "category": "Header",
        "client": "Simple Law Office",
        "orderDate": new Date(2026, 6, 5),
        "price": 1000,
        "status": "Paid",
    },
    {
        "id": 7,
        "productName": "Office-Image",
        "productType": "Photo",
        "category": "Office",
        "client": "Rizal Law Office",
        "orderDate": new Date(2026, 0, 1),
        "price": 1000,
        "status": "Paid",
    },
    {
        "id": 8,
        "productName": "Blue-Template",
        "productType": "Template",
        "category": "Blue",
        "client": "Shigetora Law Firm",
        "orderDate": new Date(2027, 6, 27),
        "price": 1000,
        "status": "Paid",
    },
    {
        "id": 9,
        "productName": "Hammer-Logo",
        "productType": "Logo",
        "category": "Hammer",
        "client": "Bautista Law Office",
        "orderDate": new Date(2026, 6, 5),
        "price": 1000,
        "status": "Paid",
    },
    {
        "id": 10,
        "productName": "Header-Text",
        "productType": "Copywrite",
        "category": "Header",
        "client": "Simple Law Office",
        "orderDate": new Date(2026, 6, 5),
        "price": 1000,
        "status": "Paid",
    },
    {
        "id": 11,
        "productName": "Office-Image",
        "productType": "Photo",
        "category": "Office",
        "client": "Rizal Law Office",
        "orderDate": new Date(2026, 0, 1),
        "price": 1000,
        "status": "Paid",
    },
    {
        "id": 12,
        "productName": "Blue-Template",
        "productType": "Template",
        "category": "Blue",
        "client": "Shigetora Law Firm",
        "orderDate": new Date(2027, 6, 27),
        "price": 1000,
        "status": "Paid",
    },
    {
        "id": 13,
        "productName": "Hammer-Logo",
        "productType": "Logo",
        "category": "Hammer",
        "client": "Bautista Law Office",
        "orderDate": new Date(2026, 6, 5),
        "price": 1000,
        "status": "Paid",
    },
    {
        "id": 14,
        "productName": "Header-Text",
        "productType": "Copywrite",
        "category": "Header",
        "client": "Simple Law Office",
        "orderDate": new Date(2026, 6, 5),
        "price": 1000,
        "status": "Paid",
    },
    {
        "id": 15,
        "productName": "Office-Image",
        "productType": "Photo",
        "category": "Office",
        "client": "Rizal Law Office",
        "orderDate": new Date(2026, 0, 1),
        "price": 1000,
        "status": "Paid",
    },
    {
        "id": 16,
        "productName": "Blue-Template",
        "productType": "Template",
        "category": "Blue",
        "client": "Shigetora Law Firm",
        "orderDate": new Date(2027, 6, 27),
        "price": 1000,
        "status": "Paid",
    },
    {
        "id": 17,
        "productName": "Hammer-Logo",
        "productType": "Logo",
        "category": "Hammer",
        "client": "Bautista Law Office",
        "orderDate": new Date(2026, 6, 5),
        "price": 1000,
        "status": "Paid",
    },
    {
        "id": 18,
        "productName": "Header-Text",
        "productType": "Copywrite",
        "category": "Header",
        "client": "Simple Law Office",
        "orderDate": new Date(2026, 6, 5),
        "price": 1000,
        "status": "Paid",
    },
    {
        "id": 19,
        "productName": "Office-Image",
        "productType": "Photo",
        "category": "Office",
        "client": "Rizal Law Office",
        "orderDate": new Date(2026, 0, 1),
        "price": 1000,
        "status": "Paid",
    },
    {
        "id": 20,
        "productName": "Blue-Template",
        "productType": "Template",
        "category": "Blue",
        "client": "Shigetora Law Firm",
        "orderDate": new Date(2027, 6, 27),
        "price": 1000,
        "status": "Paid",
    },
]

export const customRows = [
    "ID", "Client", "Vendor", "Type", "Category", "Order Date", "Status",
]

export const customOrders = [
    {
        "id": 1,
        "client": "Bautista Law Office",
        "vendor": "Bautista Law Office",
        "productType": "Logo",
        "category": "Scale",
        "orderDate": new Date(2025, 5, 6),
        "status": "Paid",
    },
    {
        "id": 2,
        "client": "Bautista Law Office",
        "vendor": "Simple Law Firm",
        "productType": "Copywrite",
        "category": "Header",
        "orderDate": new Date(2025, 9, 6),
        "status": "Paid",
    },
    {
        "id": 3,
        "client": "Rizal Law Office",
        "vendor": "Bautista Law Office",
        "productType": "Photo",
        "category": "Deal",
        "orderDate": new Date(2025, 5, 6),
        "status": "Paid",
    },
    {
        "id": 4,
        "client": "Shigetora Law Office",
        "vendor": "Simple Law Firm",
        "productType": "Template",
        "category": "Simple Blue",
        "orderDate": new Date(2025, 9, 6),
        "status": "Paid",
    },
    {
        "id": 5,
        "client": "Sick Seven Law Firm",
        "vendor": "Shigetora Law Firm",
        "productType": "Logo",
        "category": "Numeral",
        "orderDate": new Date(2025, 9, 6),
        "status": "Paid",
    },
    {
        "id": 6,
        "client": "Bautista Law Office",
        "vendor": "Bautista Law Office",
        "productType": "Logo",
        "category": "Scale",
        "orderDate": new Date(2025, 5, 6),
        "status": "Paid",
    },
    {
        "id": 7,
        "client": "Bautista Law Office",
        "vendor": "Simple Law Firm",
        "productType": "Copywrite",
        "category": "Header",
        "orderDate": new Date(2025, 9, 6),
        "status": "Paid",
    },
    {
        "id": 8,
        "client": "Rizal Law Office",
        "vendor": "Bautista Law Office",
        "productType": "Photo",
        "category": "Deal",
        "orderDate": new Date(2025, 5, 6),
        "status": "Paid",
    },
    {
        "id": 9,
        "client": "Shigetora Law Office",
        "vendor": "Simple Law Firm",
        "productType": "Template",
        "category": "Simple Blue",
        "orderDate": new Date(2025, 9, 6),
        "status": "Paid",
    },
    {
        "id": 10,
        "client": "Sick Seven Law Firm",
        "vendor": "Shigetora Law Firm",
        "productType": "Logo",
        "category": "Numeral",
        "orderDate": new Date(2025, 9, 6),
        "status": "Paid",
    },
    {
        "id": 11,
        "client": "Bautista Law Office",
        "vendor": "Bautista Law Office",
        "productType": "Logo",
        "category": "Scale",
        "orderDate": new Date(2025, 5, 6),
        "status": "Paid",
    },
    {
        "id": 12,
        "client": "Bautista Law Office",
        "vendor": "Simple Law Firm",
        "productType": "Copywrite",
        "category": "Header",
        "orderDate": new Date(2025, 9, 6),
        "status": "Paid",
    },
    {
        "id": 13,
        "client": "Rizal Law Office",
        "vendor": "Bautista Law Office",
        "productType": "Photo",
        "category": "Deal",
        "orderDate": new Date(2025, 5, 6),
        "status": "Paid",
    },
    {
        "id": 14,
        "client": "Shigetora Law Office",
        "vendor": "Simple Law Firm",
        "productType": "Template",
        "category": "Simple Blue",
        "orderDate": new Date(2025, 9, 6),
        "status": "Paid",
    },
    {
        "id": 15,
        "client": "Sick Seven Law Firm",
        "vendor": "Shigetora Law Firm",
        "productType": "Logo",
        "category": "Numeral",
        "orderDate": new Date(2025, 9, 6),
        "status": "Paid",
    },
    {
        "id": 16,
        "client": "Bautista Law Office",
        "vendor": "Bautista Law Office",
        "productType": "Logo",
        "category": "Scale",
        "orderDate": new Date(2025, 5, 6),
        "status": "Paid",
    },
    {
        "id": 17,
        "client": "Bautista Law Office",
        "vendor": "Simple Law Firm",
        "productType": "Copywrite",
        "category": "Header",
        "orderDate": new Date(2025, 9, 6),
        "status": "Paid",
    },
    {
        "id": 18,
        "client": "Rizal Law Office",
        "vendor": "Bautista Law Office",
        "productType": "Photo",
        "category": "Deal",
        "orderDate": new Date(2025, 5, 6),
        "status": "Paid",
    },
    {
        "id": 19,
        "client": "Shigetora Law Office",
        "vendor": "Simple Law Firm",
        "productType": "Template",
        "category": "Simple Blue",
        "orderDate": new Date(2025, 9, 6),
        "status": "Paid",
    },
    {
        "id": 20,
        "client": "Sick Seven Law Firm",
        "vendor": "Shigetora Law Firm",
        "productType": "Logo",
        "category": "Numeral",
        "orderDate": new Date(2025, 9, 6),
        "status": "Paid",
    },
]